/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AssignmentWithUserNameTO
 */
export interface AssignmentWithUserNameTO {
    /**
     * 
     * @type {string}
     * @memberof AssignmentWithUserNameTO
     */
    bpmnRepositoryId: any;
    /**
     * 
     * @type {string}
     * @memberof AssignmentWithUserNameTO
     */
    userName: any;
    /**
     * 
     * @type {string}
     * @memberof AssignmentWithUserNameTO
     */
    roleEnum: AssignmentWithUserNameTORoleEnumEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AssignmentWithUserNameTORoleEnumEnum {
    OWNER = 'OWNER',
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER',
    VIEWER = 'VIEWER'
}

