/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BpmnDiagramVersionTO
 */
export interface BpmnDiagramVersionTO {
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnDiagramVersionId?: any;
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnDiagramVersionComment?: any;
    /**
     * 
     * @type {number}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnDiagramVersionRelease?: any;
    /**
     * 
     * @type {number}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnDiagramVersionMilestone?: any;
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnAsXML: any;
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    saveType: BpmnDiagramVersionTOSaveTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof BpmnDiagramVersionTO
     */
    updatedDate: any;
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnDiagramId: any;
    /**
     * 
     * @type {string}
     * @memberof BpmnDiagramVersionTO
     */
    bpmnRepositoryId: any;
}

/**
    * @export
    * @enum {string}
    */
export enum BpmnDiagramVersionTOSaveTypeEnum {
    RELEASE = 'RELEASE',
    MILESTONE = 'MILESTONE',
    AUTOSAVE = 'AUTOSAVE'
}

