/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Deployment
 */
export interface Deployment {
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    target?: any;
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    user?: any;
    /**
     * 
     * @type {Date}
     * @memberof Deployment
     */
    timestamp?: any;
}
