/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DiagramVersionTO
 */
export interface DiagramVersionTO {
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    comment?: any;
    /**
     * 
     * @type {number}
     * @memberof DiagramVersionTO
     */
    release?: any;
    /**
     * 
     * @type {number}
     * @memberof DiagramVersionTO
     */
    milestone?: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    xml: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    saveType: DiagramVersionTOSaveTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof DiagramVersionTO
     */
    updatedDate: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    diagramId: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionTO
     */
    repositoryId: any;
}

/**
    * @export
    * @enum {string}
    */
export enum DiagramVersionTOSaveTypeEnum {
    RELEASE = 'RELEASE',
    MILESTONE = 'MILESTONE',
    AUTOSAVE = 'AUTOSAVE'
}

