/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DiagramVersionUploadTO
 */
export interface DiagramVersionUploadTO {
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionUploadTO
     */
    versionComment?: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionUploadTO
     */
    xml?: any;
    /**
     * 
     * @type {string}
     * @memberof DiagramVersionUploadTO
     */
    saveType?: DiagramVersionUploadTOSaveTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DiagramVersionUploadTOSaveTypeEnum {
    RELEASE = 'RELEASE',
    MILESTONE = 'MILESTONE',
    AUTOSAVE = 'AUTOSAVE'
}

