/* tslint:disable */
/* eslint-disable */

/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DiagramTO
 */
export interface DiagramTO {
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    id?: any;
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    repositoryId: any;
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    name: any;
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    description: any;
    /**
     *
     * @type {Date}
     * @memberof DiagramTO
     */
    createdDate?: any;
    /**
     *
     * @type {Date}
     * @memberof DiagramTO
     */
    updatedDate?: any;
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    svgPreview?: any;
    /**
     *
     * @type {string}
     * @memberof DiagramTO
     */
    fileType?: any;
}
