/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MenuItemTO
 */
export interface MenuItemTO {
    /**
     * 
     * @type {string}
     * @memberof MenuItemTO
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof MenuItemTO
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof MenuItemTO
     */
    icon?: any;
    /**
     * 
     * @type {number}
     * @memberof MenuItemTO
     */
    position?: any;
}
